### ISSUE TITLE
Update Gradle version

### ISSUE THREAD

**Issue by SaurabhSM** [leesnhyun/flashy_tab_bar#2]
Could not build project due to old gradle version of this package. Please update the gradle version to latest. 
Thanks

**Comment by leesnhyun** [comment]
Done. :heavy_check_mark: 
https://github.com/leesnhyun/flashy_tab_bar/pull/1

Thank you for your interesting :)

**Comment by baoxiehao** [comment]
A problem occurred evaluating root project 'flashy_tab_bar'.
> Failed to apply plugin [id 'com.android.library']
   > Minimum supported Gradle version is 5.4.1. Current version is 4.10.2. If using the gradle wrapper, try editing the distributionUrl in /Users/baoxiehao/.pub-cache/hosted/pub.flutter-io.cn/flashy_tab_bar-0.0.3/android/gradle/wrapper/gradle-wrapper.properties to gradle-5.4.1-all.zip

Same problem
